	AREA LETTER, CODE, READONLY
	ENTRY
MAIN
	LDR R3, V1
	MOV R2, #5
	MOV R1, #'E'
	MOV R6, #0
LOOP
	LDRB R4, [R3], #1
	CMP R4, R1
	ADDEQ R6, R6, #01
	SUBS R2, R2, #01
	BNE LOOP
	AREA VALUES, DATA, READONLY
V1 DCD STRING
STRING DCB "EMBED"
	END